name: Build
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
env:
  QSTASH_URL: "https://qstash.upstash.io/v2/publish/"
  QSTASH_TOKEN: "we323we"
  QSTASH_CURRENT_SIGNING_KEY: "sig_233"
  QSTASH_NEXT_SIGNING_KEY: "sig_232"
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Build
      run: yarn build
